export const ACTIVITY_TYPES = [
  { label: 'Trčanje', value: 'Running' },
  { label: 'Biciklizam', value: 'Cycling' },
  { label: 'Plivanje', value: 'Swimming' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Ostalo', value: 'Other' },
  { label: 'Planinarenje', value: 'Hiking' },
  { label: 'Joga', value: 'Yoga' },
  { label: 'CrossFit', value: 'CrossFit' },
  { label: 'Pilates', value: 'Pilates' },
  { label: 'Tenis', value: 'Tennis' },
  { label: 'Košarka', value: 'Basketball' },
  { label: 'Fudbal', value: 'Football' },
  { label: 'Odbojka', value: 'Volleyball' },
  { label: 'Rukomet', value: 'Handball' },
  { label: 'Skijanje', value: 'Skiing' },
  { label: 'Snowboarding', value: 'Snowboarding' },
  { label: 'Kuglanje', value: 'Bowling' },
  { label: 'Stoni tenis', value: 'TableTennis' },
  { label: 'Badminton', value: 'Badminton' },
  { label: 'Ples', value: 'Dancing' },
  { label: 'Aerobik', value: 'Aerobics' },
  { label: 'Zumba', value: 'Zumba' },
  { label: 'Boks', value: 'Boxing' },
  { label: 'Kickboks', value: 'Kickboxing' },
  { label: 'Borilačke veštine', value: 'MartialArts' },
  { label: 'Triatlon', value: 'Triathlon' },
  { label: 'Kajak', value: 'Kayaking' },
  { label: 'Veslanje', value: 'Rowing' },
  { label: 'Surfovanje', value: 'Surfing' },
  { label: 'Jedrenje', value: 'Sailing' },
  { label: 'Pecanje', value: 'Fishing' },
  { label: 'Jahanje', value: 'HorseRiding' },
  { label: 'Golf', value: 'Golf' },
  { label: 'Atletika', value: 'Athletics' },
  { label: 'Skakanje u vis', value: 'HighJump' },
  { label: 'Skakanje u dalj', value: 'LongJump' },
  { label: 'Kugla', value: 'ShotPut' },
  { label: 'Disk', value: 'DiscusThrow' },
  { label: 'Kuglanje', value: 'Bowling' },
  { label: 'Biciklistički kros', value: 'Cyclocross' },
  { label: 'Veslanje na dasci', value: 'Paddleboarding' },
  { label: 'Klizanje', value: 'IceSkating' },
  { label: 'Brzo hodanje', value: 'SpeedWalking' }
];
